<?php 

namespace odiseIAFramework;

// HERE IS ALL THE FUNCTIONS TO PONDER THE NATIVE BLOCKS AND GUTEMBERG FUNCTIONALITIES

class Ponder{

    public static function init()
    {
        add_action('enqueue_block_editor_assets', [__CLASS__,'odiseia_responsive_options']);
        add_action('enqueue_block_assets', [__CLASS__,'odiseia_responsive_styles']);
    }

    public static function odiseia_responsive_options()
    {
        // Dependencies and version come from build/Plugins/{name}.asset.php, generated by wp-scripts.
        Assets::enqueue_plugin_script('odiseiaframework-responsive', 'responsive');

        // Assets::enqueue_plugin_script('odiseiaframework-responsive-spacing', 'responsiveSpacing');
    }

    public static function odiseia_responsive_styles()
    {
        wp_enqueue_style(
            'gutemberg-responsive-css',
            ODISEIAFRAMEWORK_URL.'assets/responsive.css',
            array()
        );
    }

}